### ISSUE TITLE
Add some more output

### ISSUE THREAD

**Issue by koppor** [maheshrayas/action-pr-comment-delete#7]
I have

```yaml
      - name: Remove all comments by "github-actions[bot]"
        if: ${{ steps.read-pr_number.outputs.pr_number != '' && steps.isCrossRepository.outputs.isCrossRepository == 'true' }}
        uses: maheshrayas/action-pr-comment-delete@v3.0
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          org: JabRef
          repo: jabref
          user: 'github-actions[bot]' #commented by the userid
          issue: '${{ steps.read-pr_number.outputs.pr_number }}'
```

Output of action:

```
 ##[debug]Loading env
Run maheshrayas/action-pr-comment-delete@v3.0
  with:
    github_token: ***
    org: JabRef
    repo: jabref
    user: github-actions[bot]
    issue: 12710
/usr/bin/docker run --name maheshrayasprcommentdeleter30_fce396 --label ba53b4 --workdir /github/workspace --rm -e "INPUT_GITHUB_TOKEN" -e "INPUT_ORG" -e "INPUT_REPO" -e "INPUT_USER" -e "INPUT_ISSUE" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_DEBUG" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/jabref/jabref":"/github/workspace" maheshrayas/pr-comment-deleter:3.0
##[debug]Docker Action run completed with exit code 0
```

I would assume the following comment was removed:

![Image](https://github.com/user-attachments/assets/145e558b-aed8-4198-96a2-288625507263)

But it did not.

Thus, I would like to have some way of debug.

`core.debug` offers debbugging

`ACTIONS_STEP_DEBUG` `true` secreat

See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging
